"""Text encoder for 2D datamatrix barcode encoder"""

__revision__ = "$Rev$"

import logging

from pystrich.exceptions import PyStrichInvalidInput

from .data import DataMatrixCodeword, DataMatrixData, fnc1_workaround_compat
from .reedsolomon import get_reed_solomon_code

log = logging.getLogger("datamatrix")

data_word_length = (3, 5, 8, 12, 18, 22, 30, 36, 44,
                    62, 86, 114, 144, 174, 204,
                    280, 368, 456, 576, 696, 816,
                    1050, 1304, 1558)

error_word_length = (5, 7, 10, 12, 14, 18, 20, 24, 28,
                     36, 42, 48, 56, 68, 84,
                     112, 144, 192, 224, 272, 336,
                     408, 496, 620)

data_region_size = (8, 10, 12, 14, 16, 18, 20, 22, 24,
                    14, 16, 18, 20, 22, 24,
                    14, 16, 18, 20, 22, 24,
                    18, 20, 22)

hv_regions = (1, 1, 1, 1, 1, 1, 1, 1, 1,
              2, 2, 2, 2, 2, 2,
              4, 4, 4, 4, 4, 4,
              6, 6, 6)


class DataTooLongForImplementation(PyStrichInvalidInput):
    pass


class TextEncoder:
    """Text encoder class for 2D datamatrix"""

    def __init__(self):
        self.codewords = ''
        self.size_index = None
        self.mtx_size = 0
        self.regions = None

    def encode(self, text):
        """Encode the given text and add padding and error codes
        also set up the correct matrix size for the resulting codewords"""

        self.__init__()

        self.encode_text(text)

        self.pad()

        self.append_error_codes()

        log.debug(
            "Codewords: " +
            ' '.join([str(ord(codeword)) for codeword in self.codewords]))

        self.mtx_size = data_region_size[self.size_index]
        self.regions = hv_regions[self.size_index]

        log.debug("Matrix size will be %d", self.mtx_size)

        return self.codewords

    def encode_text(self, text):
        """Encode the given text into codewords"""

        data = text if isinstance(text, DataMatrixData) else fnc1_workaround_compat(text)

        if data.encoding == "utf-8":
            # Codeword 241 (ECI) + 27 (ECI value 26 + 1) declares UTF-8 for the
            # remainder of the symbol. Emitted once, before any data.
            self.append_codeword(241)
            self.append_codeword(27)

        numbuf = ''

        def flush_numbuf():
            nonlocal numbuf
            if len(numbuf) == 2:
                self.append_digits(numbuf)
            elif numbuf:
                self.append_ascii_char(numbuf)
            numbuf = ''

        for segment in data.segments:
            if isinstance(segment, DataMatrixCodeword):
                flush_numbuf()
                self.append_codeword(segment.value)
                continue

            # For UTF-8 we work over the byte sequence (each byte rendered as a
            # 1-char string); for everything else, iterate the codepoints directly.
            chars = (chr(b) for b in segment.encode("utf-8")) if data.encoding == "utf-8" else segment

            for char in chars:
                if data.encoding in ("iso-8859-1", "utf-8") and ord(char) > 127:
                    flush_numbuf()
                    self.append_upper_shift_byte(ord(char))
                elif "0" <= char <= "9":
                    numbuf += char
                    if len(numbuf) == 2:
                        flush_numbuf()
                else:
                    flush_numbuf()
                    self.append_ascii_char(char)

        flush_numbuf()

    def pad(self):
        """Pad out the encoded text to the correct word length"""

        unpadded_len = len(self.codewords)
        log.debug("Unpadded data size:   %d bytes", unpadded_len)

        # Work out how big the matrix needs to be
        for self.size_index, length in enumerate(data_word_length):
            if length >= unpadded_len:
                break

        if self.size_index > 13:
            raise DataTooLongForImplementation("PyStrich does not currently support encoding beyond 174 characters. "
                                               "See https://github.com/mmulqueen/pyStrich/issues/2")

        # Number of characters with which the data will be padded
        padsize = length - unpadded_len

        log.debug("Pad size: %d bytes", padsize)

        # First pad character is 129
        if padsize:
            self.append_codeword(129)

        def rand253(pos):
            """generate the next padding character"""
            rnd = ((149 * pos) % 253) + 1
            return (129 + rnd) % 254

        # Remaining pad characters generated by 253-state algorithm
        for i in range(1, padsize):
            self.append_codeword(rand253(unpadded_len + i + 1))

        log.debug("Word size after padding: %d bytes", len(self.codewords))

    def append_error_codes(self):
        """Calculate the necessary number of Reed Solomon error codes for the
        encoded text and padding codewords, and append to the codeword buffer"""

        error_length = error_word_length[self.size_index]
        log.debug("Error word length: %d bytes", error_length)

        error_words = get_reed_solomon_code(self.codewords, error_length)

        self.codewords += error_words

    def append_codeword(self, value):
        """Append a single codeword to the buffer."""

        self.codewords += chr(value)

    def append_digits(self, digits):
        """Write a pair of digits
        (the appended value is 130 + the integer value of the digits together"""

        value = 130 + int(digits)
        self.append_codeword(value)

    def append_ascii_char(self, char):
        """Append a single ascii character
        (the appended value is the value of the char plus 1"""

        value = ord(char) + 1
        self.append_codeword(value)

    def append_upper_shift_byte(self, byte_value):
        """Append a byte in 128-255 via Upper Shift (codeword 235)."""

        self.append_codeword(235)
        self.append_ascii_char(chr(byte_value - 128))
