"""Regenerate ``pystrich/_courier_glyphs.py`` from the bundled Courier Prime TTF.

Reads ``courier_prime/CourierPrime-Regular.ttf`` and writes outline path
data for the printable-ASCII range (0x20-0x7E) into a Python module that
ships inside the package. SVG and EPS renderers consume that data to
draw the human-readable label below 1D barcodes — see ``pystrich/svg.py``
and ``pystrich/eps.py``.

This script is not run by the test suite or build; it only needs to run
when the source font changes. ``fontTools`` is part of the ``dev`` Poetry
group (already a transitive dependency of ezdxf):

    poetry install --with dev
    poetry run --no-interaction python scripts/generate_courier_glyphs.py
"""

from __future__ import annotations

import sys
from pathlib import Path

from fontTools.pens.qu2cuPen import Qu2CuPen
from fontTools.pens.recordingPen import DecomposingRecordingPen, RecordingPen
from fontTools.ttLib import TTFont

REPO_ROOT = Path(__file__).resolve().parent.parent
TTF_PATH = REPO_ROOT / "courier_prime" / "CourierPrime-Regular.ttf"
OFL_PATH = REPO_ROOT / "courier_prime" / "OFL.txt"
OUT_PATH = REPO_ROOT / "pystrich" / "_courier_glyphs.py"

PRINTABLE_ASCII = range(0x20, 0x7F)

# Qu2CuPen tolerance in font units. The font is at UPM 1000 and we render
# labels at ~24 px max in practice (≈ 42 font units per pixel), so a 1-unit
# error budget is well under one rendered pixel.
QU2CU_MAX_ERR = 1.0


def _fmt(value: float) -> str:
    return str(round(value))


def _ops_to_svg_d(operations: list[tuple]) -> str:
    parts: list[str] = []
    for op, args in operations:
        if op == "moveTo":
            ((x, y),) = args
            parts.append(f"M{_fmt(x)} {_fmt(y)}")
        elif op == "lineTo":
            ((x, y),) = args
            parts.append(f"L{_fmt(x)} {_fmt(y)}")
        elif op == "curveTo":
            (x1, y1), (x2, y2), (x3, y3) = args
            parts.append(
                f"C{_fmt(x1)} {_fmt(y1)} {_fmt(x2)} {_fmt(y2)} "
                f"{_fmt(x3)} {_fmt(y3)}"
            )
        elif op == "closePath":
            parts.append("Z")
        elif op == "endPath":
            continue
        else:
            raise ValueError(f"Unsupported pen operation: {op}")
    return " ".join(parts)


def _ops_to_eps_body(operations: list[tuple]) -> str:
    parts: list[str] = []
    for op, args in operations:
        if op == "moveTo":
            ((x, y),) = args
            parts.append(f"{_fmt(x)} {_fmt(y)} moveto")
        elif op == "lineTo":
            ((x, y),) = args
            parts.append(f"{_fmt(x)} {_fmt(y)} lineto")
        elif op == "curveTo":
            (x1, y1), (x2, y2), (x3, y3) = args
            parts.append(
                f"{_fmt(x1)} {_fmt(y1)} {_fmt(x2)} {_fmt(y2)} "
                f"{_fmt(x3)} {_fmt(y3)} curveto"
            )
        elif op == "closePath":
            parts.append("closepath")
        elif op == "endPath":
            continue
        else:
            raise ValueError(f"Unsupported pen operation: {op}")
    return " ".join(parts)


def _extract_glyph(glyph_set, glyph_name: str) -> tuple[str, str, int]:
    # Two-stage pipeline: first record the glyph with composite references
    # decomposed (DecomposingRecordingPen), then replay through Qu2CuPen so
    # every quadratic Bézier becomes a cubic. The final recording therefore
    # contains only moveTo/lineTo/curveTo/closePath/endPath.
    decomposed = DecomposingRecordingPen(glyph_set)
    glyph = glyph_set[glyph_name]
    glyph.draw(decomposed)

    cubic = RecordingPen()
    decomposed.replay(Qu2CuPen(cubic, max_err=QU2CU_MAX_ERR, all_cubic=True))
    return _ops_to_svg_d(cubic.value), _ops_to_eps_body(cubic.value), glyph.width


def _render_module(
    em_size: int,
    advance: int,
    ascent: int,
    descent: int,
    glyphs: list[tuple[str, str, str]],
    ofl_text: str,
) -> str:
    if '"""' in ofl_text:
        raise ValueError(
            "OFL text contains ``\"\"\"`` which would terminate the embedded "
            "string literal; adjust the embedding strategy."
        )
    lines = [
        '"""Embedded Courier Prime glyph outlines for SVG/EPS labels.',
        "",
        "Generated by ``scripts/generate_courier_glyphs.py`` from",
        "``courier_prime/CourierPrime-Regular.ttf``. Do not hand-edit; re-run",
        "the generator if the source font changes.",
        "",
        "Courier Prime is distributed under the SIL Open Font License, Version 1.1;",
        "the upstream license text is bundled inline as ``OFL_LICENSE`` below so",
        "wheel users receive it alongside the derived glyph outlines.",
        "",
        "Coordinates are in the font's native em-up space (y-axis up, baseline at",
        "y=0). Renderers apply the appropriate translate/scale (and y-flip for SVG)",
        "to place glyphs into output coordinates.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import NamedTuple",
        "",
        "",
        f"EM_SIZE = {em_size}",
        f"ADVANCE = {advance}",
        f"ASCENT = {ascent}",
        f"DESCENT = {descent}",
        "",
        "",
        'OFL_LICENSE = """',
        ofl_text.rstrip("\n"),
        '"""',
        "",
        "",
        "class Glyph(NamedTuple):",
        "    svg_d: str",
        "    eps_body: str",
        "",
        "",
        "GLYPHS: dict[str, Glyph] = {",
    ]
    for char, svg_d, eps_body in glyphs:
        lines.append(
            f"    {char!r}: Glyph(svg_d={svg_d!r}, eps_body={eps_body!r}),"
        )
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> int:
    if not TTF_PATH.exists():
        print(f"Font file not found: {TTF_PATH}", file=sys.stderr)
        return 1
    if not OFL_PATH.exists():
        print(f"OFL license file not found: {OFL_PATH}", file=sys.stderr)
        return 1

    ofl_text = OFL_PATH.read_text(encoding="utf-8")
    font = TTFont(TTF_PATH)
    cmap = font.getBestCmap()
    glyph_set = font.getGlyphSet()
    em_size = font["head"].unitsPerEm
    hhea = font["hhea"]
    ascent = hhea.ascent
    descent = -hhea.descent

    advances: set[int] = set()
    glyphs: list[tuple[str, str, str]] = []
    for codepoint in PRINTABLE_ASCII:
        glyph_name = cmap.get(codepoint)
        if glyph_name is None:
            print(
                f"Codepoint {codepoint:#04x} missing from cmap; aborting.",
                file=sys.stderr,
            )
            return 1
        svg_d, eps_body, width = _extract_glyph(glyph_set, glyph_name)
        advances.add(width)
        glyphs.append((chr(codepoint), svg_d, eps_body))

    if len(advances) != 1:
        print(
            f"Expected uniform advance for printable ASCII but got {sorted(advances)};"
            " the renderer assumes a constant ADVANCE.",
            file=sys.stderr,
        )
        return 1
    advance = advances.pop()

    OUT_PATH.write_text(
        _render_module(em_size, advance, ascent, descent, glyphs, ofl_text)
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
